#!/bin/sh
# chkconfig: 345 90 10
# description: Runs DataSpiderServer

progname="DataSpiderServer"
lockfile=/var/lock/subsys/$progname
dshome=/usr/local/dataspider/server
startcmd=$dshome/bin/DataSpiderServer
stopcmd=$dshome/bin/Shutdown
serverlog=$dshome/logs/server.log
errorfile=$dshome/error
user=ec2-user

RETVAL=0

start() {
  if [ -e $lockfile ]; then
    echo "$progname is running now."
    return 1
  fi
  echo "Starting $progname: "
  su -l $user -c $startcmd || su -l $user -c "touch $errorfile" &
  while :; do
    if tail $serverlog | grep --silent "正常に起動しました。"; then
        touch $lockfile
        RETVAL=0
        break
    elif [ -e $errorfile ]; then
        rm $errorfile
        RETVAL=1
        break
    fi
  done
  echo ""
  return $RETVAL
}

stop() {
  if [ ! -e $lockfile ]; then
    echo "$progname is not running."
    return 1
  fi
  echo "Stopping $progname: "
  su -l $user -c $stopcmd || su -l $user -c "touch $errorfile" &
  while :; do
    if tail $serverlog | grep --silent "停止しました。"; then
      rm -f $lockfile
      RETVAL=0
      break
    elif [ -e $errorfile ]; then
      rm $errorfile
      RETVAL=1
      break
    fi
  done
  echo ""
  return $RETVAL
}

status() {
  if [ -e $lockfile ]; then
    echo "$progname is running"
  else
    echo "$progname is stopped"
  fi
  return 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    sleep 1
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $RETVAL
